name: Cypress Test Workflow

on:
  push:
    branches:
      - main

jobs:
  ecom-tests:
    runs-on: [self-hosted, linux]  # Specify the self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
