name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Ensure the job runs on Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  # Install project dependencies

      - name: Install Cypress Dependencies
        run: npm ci  # Ensures Cypress and other dependencies are installed

      - name: Set executable permissions for Cypress binary
        run: chmod +x ./node_modules/.bin/cypress  # Ensure the Cypress binary is executable

      - name: Run Cypress Tests
        run: npx cypress run  # Run Cypress using npx
